import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = localFont({
  src: "../fonts/Montserrat-Bold.ttf",
  variable: "--font-montserrat",
});
const montserratReg = localFont({
  src: "../fonts/Montserrat-Light.ttf",
  variable: "--font-montserrat-reg",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${montserratReg.variable} antialiased`}
        >
          {children}
        </body>
    </html>
  );
}
